### PR TITLE
[Docs] Change slack join link to badge

### PR DESCRIPTION
**Pull request by frank-zsy**
Signed-off-by: Frankzhaopku <syzhao1988@126.com>

Change join `Slack` link from text to a badge to better presentation.

### CODE REVIEW

**Comment by frank-zsy** [comment]
Also add `Apache license` and `CC-BY-4.0 license` file link on the badge.

**Comment by sunshinemingo** [comment]
I think this is a good idea. But if we change Slack join link to badge, I wonder whether to keep the text about joining Slack.

**Comment by frank-zsy** [comment]
> I think this is a good idea. But if we change Slack join link to badge, I wonder whether to keep the text about joining Slack.

I think we don't need the text so I removed the text part as well, WDYT?

**Comment by sunshinemingo** [comment]
Maybe there is such a situation. Someone may ignore the slack badge when browsing readme file, so that he can not find a way to communicate with us. Maybe we can add a guidance like this in readme: if you are interested in our project, you can join us through slack badge.

**Comment by frank-zsy** [comment]
That is right, I updated the PR.

**Pull request merged**
